name: ztdlbook
channels:
- defaults
dependencies:
- python=3.6
- pip==9.0.1
- numpy==1.14.0
- jupyter==1.0.0
- matplotlib==2.1.2
- scikit-learn==0.19.1
- scipy==1.0.0
- pandas==0.22.0
- pillow==5.0.0
- seaborn==0.8.1
- h5py==2.7.1
- pytest==3.3.2
- pip:
  - tensorflow==1.5.0
  - keras==2.1.3
  - jupyter_contrib_nbextensions==0.4.0
